name: Version and Release

on:
  push:
    branches:
      - main


jobs:
  version_and_release:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    # Job name, can be anything
    name: Export Game Job
    steps:
    - name: checkout
      uses: actions/checkout@v2
      # Ensure that you get the entire project history
      with:
        fetch-depth: 0
    - name: Release on push
      id: release
      uses: rymndhng/release-on-push-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        bump_version_scheme: patch
        use_github_release_notes: true
      # Always include the checkout step so that
      # your project is available for Godot to export
    - name: Commit new version
      run: |
          sed -i 's/GAME_VERSION := ".*"/GAME_VERSION := "${{ steps.release.outputs.version }}"/g' ./src/dreamscape/CFConst.gd
          git config user.email github-actions@github.com
          git config user.name github-actions
          git commit -am 'version incremented'
          git push